### ISSUE TITLE
project is incomplete

### ISSUE THREAD

**Issue by peterwatsa** [Bikash300895/Blood-Bank#4]
This project is template, no database, no apk, no completed

**Comment by ShuvenduRoy** [comment]
@peterwatsa It has all the code. It is connected to an online database. You want me to add the credentials too in a public repo? Why I have to upload apk in github?

**Comment by peterwatsa** [comment]
Hi Shuvendu...
This App is excellent demo example.
I didn't run it & i forget to closed the issue.
